# Layer configurations for yolov10
layer_configs = [
    # Layer 1
    {
        'params': {
            'tile_height': {'total': 640, 'tile': 20},
            'tile_width': {'total': 480, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': 'MAXPOOL', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 77},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00000000,
            'IN1_offset': 0x01000000,
            'output1_offset': 0x0112c000,
            'param_offset': 0x10000000,
        },
        'operation': 'D2_CONV',
    },
    # Layer 2
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 16, 'tile': 16},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 1260},
            'quant_param2': {'shift': 14, 'scale': 425},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00000240,
            'IN1_offset': 0x0112c000,
            'output1_offset': 0x01177000,
            'output2_offset': 0x0120d000,
            'param_offset': 0x10000020,
        },
        'operation': 'D2_CONV',
    },
    # Layer 3
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 16, 'tile': 16},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 198},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00000e40,
            'IN1_offset': 0x011c2000,
            'output1_offset': 0x012ee000,
            'param_offset': 0x100000a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 4
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 16, 'tile': 16},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 187},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00001740,
            'IN1_offset': 0x012ee000,
            'output1_offset': 0x01339000,
            'param_offset': 0x100000c0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 5
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01339000,
            'IN2_offset': 0x01258000,
            'output1_offset': 0x012a3000,
        },
        'operation': 'EWADDER',
    },
    # Layer 6
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 48, 'tile': 16},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 385},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00000540,
            'IN1_offset': 0x0120d000,
            'output1_offset': 0x01384000,
            'param_offset': 0x10000060,
        },
        'operation': 'D2_CONV',
    },
    # Layer 7
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 212},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00002040,
            'IN1_offset': 0x01384000,
            'output1_offset': 0x0141a000,
            'param_offset': 0x100000e0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 8
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 264},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00006840,
            'IN1_offset': 0x0141a000,
            'output1_offset': 0x01465000,
            'param_offset': 0x10000160,
        },
        'operation': 'D2_CONV',
    },
    # Layer 9
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 425},
            'quant_param2': {'shift': 14, 'scale': 425},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00009840,
            'IN1_offset': 0x01465000,
            'output1_offset': 0x014fb000,
            'output2_offset': 0x01520800,
            'param_offset': 0x10000260,
        },
        'operation': 'DW_CONV',
    },
    # Layer 10
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 129},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00009cc0,
            'IN1_offset': 0x014fb000,
            'output1_offset': 0x01546000,
            'param_offset': 0x10000360,
        },
        'operation': 'D2_CONV',
    },
    # Layer 11
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 262},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00051cc0,
            'IN1_offset': 0x01546000,
            'output1_offset': 0x01558c00,
            'param_offset': 0x10000560,
        },
        'operation': 'D2_CONV',
    },
    # Layer 12
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 1, 'l_ovlp': 0, 'r_ovlp': 1, 'pad_type': 1, 't_pad': 0, 'b_pad': 1, 'l_pad': 0, 'r_pad': 1},
            'operation_cfg': {'operation': 'MAIN_PRCS', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'MAXPOOL', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01558c00,
            'output1_offset': 0x01562200,
        },
        'operation': 'MAIN_PRCS',
    },
    # Layer 13
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 1, 'l_ovlp': 0, 'r_ovlp': 1, 'pad_type': 1, 't_pad': 0, 'b_pad': 1, 'l_pad': 0, 'r_pad': 1},
            'operation_cfg': {'operation': 'MAIN_PRCS', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'MAXPOOL', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01562200,
            'output1_offset': 0x0156b800,
        },
        'operation': 'MAIN_PRCS',
    },
    # Layer 14
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 1, 'l_ovlp': 0, 'r_ovlp': 1, 'pad_type': 1, 't_pad': 0, 'b_pad': 1, 'l_pad': 0, 'r_pad': 1},
            'operation_cfg': {'operation': 'MAIN_PRCS', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'MAXPOOL', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x0156b800,
            'output1_offset': 0x01574e00,
        },
        'operation': 'MAIN_PRCS',
    },
    # Layer 15
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 512, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 132},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0005dcc0,
            'IN1_offset': 0x01558c00,
            'output1_offset': 0x0157e400,
            'param_offset': 0x10000660,
        },
        'operation': 'D2_CONV',
    },
    # Layer 16
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 3, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 303},
            'quant_param2': {'shift': 14, 'scale': 275},
            'quant_param3': {'shift': 14, 'scale': 287},
            'quant_param4': {'shift': 14, 'scale': 287},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0008dcc0,
            'IN1_offset': 0x0157e400,
            'output1_offset': 0x01591000,
            'output2_offset': 0x015a3c00,
            'output3_offset': 0x015b6800,
            'output4_offset': 0x015c9400,
            'param_offset': 0x10000860,
        },
        'operation': 'D2_CONV',
    },
    # Layer 17
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 10},
            'quant_param2': {'shift': 14, 'scale': 211},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000bdcc0,
            'IN1_offset': 0x0159a600,
            'output1_offset': 0x015dc000,
            'output2_offset': 0x015eec00,
            'param_offset': 0x10000c60,
        },
        'operation': 'D2_CONV',
    },
    # Layer 18
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'MATMUL', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 2730},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 16, 'scale': 2730},
            'C_CONCAT': 2,
            'weight_offset': 0x015dc000,
            'IN1_offset': 0x015de580,
            'IN2_offset': 0x015e0b00,
            'output1_offset': 0x01601800,
        },
        'operation': 'MATMUL',
    },
    # Layer 19
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'MATMUL', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 2730},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 16, 'scale': 2730},
            'C_CONCAT': 2,
            'weight_offset': 0x015e5600,
            'IN1_offset': 0x015e7b80,
            'IN2_offset': 0x015ea100,
            'output1_offset': 0x01606300,
        },
        'operation': 'MATMUL',
    },
    # Layer 20
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 65},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000cfcc0,
            'IN1_offset': 0x015f3700,
            'output1_offset': 0x0160ae00,
            'param_offset': 0x10000f60,
        },
        'operation': 'DW_CONV',
    },
    # Layer 21
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 65},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000cff00,
            'IN1_offset': 0x015fcd00,
            'output1_offset': 0x0160f900,
            'param_offset': 0x10000fe0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 22
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x0160ae00,
            'IN2_offset': 0x01601800,
            'output1_offset': 0x01614400,
        },
        'operation': 'EWADDER',
    },
    # Layer 23
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 84},
            'quant_param2': {'shift': 14, 'scale': 88},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000c9cc0,
            'IN1_offset': 0x01614400,
            'output1_offset': 0x0161da00,
            'output2_offset': 0x01627000,
            'param_offset': 0x10000e60,
        },
        'operation': 'D2_CONV',
    },
    # Layer 24
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x015ad200,
            'IN2_offset': 0x0161da00,
            'output1_offset': 0x01630600,
        },
        'operation': 'EWADDER',
    },
    # Layer 25
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 186},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000d0140,
            'IN1_offset': 0x01630600,
            'output1_offset': 0x01639c00,
            'param_offset': 0x10001060,
        },
        'operation': 'D2_CONV',
    },
    # Layer 26
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 39},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000dc140,
            'IN1_offset': 0x01639c00,
            'output1_offset': 0x0164c800,
            'param_offset': 0x10001260,
        },
        'operation': 'D2_CONV',
    },
    # Layer 27
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x015bfe00,
            'IN2_offset': 0x01627000,
            'output1_offset': 0x01655e00,
        },
        'operation': 'EWADDER',
    },
    # Layer 28
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01655e00,
            'IN2_offset': 0x0164c800,
            'output1_offset': 0x015d2a00,
        },
        'operation': 'EWADDER',
    },
    # Layer 29
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 107},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000a5cc0,
            'IN1_offset': 0x015c9400,
            'output1_offset': 0x0165f400,
            'param_offset': 0x10000a60,
        },
        'operation': 'D2_CONV',
    },
    # Layer 30
    {
        'params': {
            'tile_height': {'total': 30, 'tile': 30},
            'tile_width': {'total': 40, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'RESIZE', 'kernel_size': 2, 'stride': 1, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01520800,
            'output1_offset': 0x0167b600,
        },
        'operation': 'RESIZE',
    },
    # Layer 31
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 99},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000e8140,
            'IN1_offset': 0x0167b600,
            'output1_offset': 0x01711600,
            'param_offset': 0x10001360,
        },
        'operation': 'D2_CONV',
    },
    # Layer 32
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': 'MAXPOOL', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 106},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00130140,
            'IN1_offset': 0x01711600,
            'output1_offset': 0x01672000,
            'param_offset': 0x10001560,
        },
        'operation': 'D2_CONV',
    },
    # Layer 33
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 384, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 682},
            'quant_param2': {'shift': 14, 'scale': 182},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00178140,
            'IN1_offset': 0x0165f400,
            'output1_offset': 0x0183d600,
            'output2_offset': 0x01850200,
            'param_offset': 0x10001660,
        },
        'operation': 'D2_CONV',
    },
    # Layer 34
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 546},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001c0140,
            'IN1_offset': 0x01846c00,
            'output1_offset': 0x0186c400,
            'param_offset': 0x10001a60,
        },
        'operation': 'DW_CONV',
    },
    # Layer 35
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 442},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001c05c0,
            'IN1_offset': 0x0186c400,
            'output1_offset': 0x01875a00,
            'param_offset': 0x10001b60,
        },
        'operation': 'D2_CONV',
    },
    # Layer 36
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 520},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001cc5c0,
            'IN1_offset': 0x01875a00,
            'output1_offset': 0x01888600,
            'param_offset': 0x10001d60,
        },
        'operation': 'DW_CONV',
    },
    # Layer 37
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 315},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001ccec0,
            'IN1_offset': 0x01888600,
            'output1_offset': 0x0189b200,
            'param_offset': 0x10001f60,
        },
        'operation': 'D2_CONV',
    },
    # Layer 38
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 385},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001d8ec0,
            'IN1_offset': 0x0189b200,
            'output1_offset': 0x018a4800,
            'param_offset': 0x10002060,
        },
        'operation': 'DW_CONV',
    },
    # Layer 39
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01859800,
            'IN2_offset': 0x018a4800,
            'output1_offset': 0x01862e00,
        },
        'operation': 'EWADDER',
    },
    # Layer 40
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 384, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 327},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0019c140,
            'IN1_offset': 0x01850200,
            'output1_offset': 0x018ade00,
            'param_offset': 0x10001860,
        },
        'operation': 'D2_CONV',
    },
    # Layer 41
    {
        'params': {
            'tile_height': {'total': 0, 'tile': 0},
            'tile_width': {'total': 0, 'tile': 0},
            'tile_in_ch': {'total': 0, 'tile': 0},
            'tile_out_ch': {'total': 0, 'tile': 0},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
        },
        'operation': 'D2_CONV',
    },
]
