# Layer configurations for yolov10
layer_configs = [
    # Layer 1
    {
        'params': {
            'tile_height': {'total': 640, 'tile': 20},
            'tile_width': {'total': 480, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 127},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00000000,
            'IN1_offset': 0x01000000,
            'output1_offset': 0x0112c000,
            'param_offset': 0x10000000,
        },
        'operation': 'D2_CONV',
    },
    # Layer 2
    {
        'params': {
            'tile_height': {'total': 320, 'tile': 20},
            'tile_width': {'total': 240, 'tile': 20},
            'tile_in_ch': {'total': 16, 'tile': 16},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 277},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00000240,
            'IN1_offset': 0x0112c000,
            'output1_offset': 0x01258000,
            'param_offset': 0x10000020,
        },
        'operation': 'D2_CONV',
    },
    # Layer 3
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 1129},
            'quant_param2': {'shift': 14, 'scale': 455},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00001440,
            'IN1_offset': 0x01258000,
            'output1_offset': 0x012ee000,
            'output2_offset': 0x01384000,
            'param_offset': 0x10000060,
        },
        'operation': 'D2_CONV',
    },
    # Layer 4
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 16, 'tile': 16},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 512},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00002340,
            'IN1_offset': 0x01339000,
            'output1_offset': 0x01465000,
            'param_offset': 0x100000e0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 5
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 16, 'tile': 16},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 149},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00002c40,
            'IN1_offset': 0x01465000,
            'output1_offset': 0x014b0000,
            'param_offset': 0x10000100,
        },
        'operation': 'D2_CONV',
    },
    # Layer 6
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x014b0000,
            'IN2_offset': 0x013cf000,
            'output1_offset': 0x0141a000,
        },
        'operation': 'EWADDER',
    },
    # Layer 7
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 48, 'tile': 16},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 489},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00001a40,
            'IN1_offset': 0x01384000,
            'output1_offset': 0x014fb000,
            'param_offset': 0x100000a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 8
    {
        'params': {
            'tile_height': {'total': 160, 'tile': 20},
            'tile_width': {'total': 120, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 196},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00003540,
            'IN1_offset': 0x014fb000,
            'output1_offset': 0x01591000,
            'param_offset': 0x10000120,
        },
        'operation': 'D2_CONV',
    },
    # Layer 9
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 2, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 630},
            'quant_param2': {'shift': 14, 'scale': 436},
            'quant_param3': {'shift': 14, 'scale': 227},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00007d40,
            'IN1_offset': 0x01591000,
            'output1_offset': 0x015dc000,
            'output2_offset': 0x01627000,
            'output3_offset': 0x01672000,
            'param_offset': 0x100001a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 10
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 157},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0000c540,
            'IN1_offset': 0x01601800,
            'output1_offset': 0x01708000,
            'param_offset': 0x100002a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 11
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 135},
            'quant_param2': {'shift': 14, 'scale': 70},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0000e940,
            'IN1_offset': 0x01708000,
            'output1_offset': 0x0172d800,
            'output2_offset': 0x01753000,
            'param_offset': 0x100002e0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 12
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x0172d800,
            'IN2_offset': 0x0164c800,
            'output1_offset': 0x01778800,
        },
        'operation': 'EWADDER',
    },
    # Layer 13
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 221},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00010d40,
            'IN1_offset': 0x01778800,
            'output1_offset': 0x0179e000,
            'param_offset': 0x10000320,
        },
        'operation': 'D2_CONV',
    },
    # Layer 14
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 158},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00013140,
            'IN1_offset': 0x0179e000,
            'output1_offset': 0x017c3800,
            'param_offset': 0x10000360,
        },
        'operation': 'D2_CONV',
    },
    # Layer 15
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01753000,
            'IN2_offset': 0x01697800,
            'output1_offset': 0x016bd000,
        },
        'operation': 'EWADDER',
    },
    # Layer 16
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x016bd000,
            'IN2_offset': 0x017c3800,
            'output1_offset': 0x016e2800,
        },
        'operation': 'EWADDER',
    },
    # Layer 17
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 352},
            'quant_param2': {'shift': 14, 'scale': 344},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00009540,
            'IN1_offset': 0x01672000,
            'output1_offset': 0x017e9000,
            'output2_offset': 0x018ca000,
            'param_offset': 0x10000220,
        },
        'operation': 'D2_CONV',
    },
    # Layer 18
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 390},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00015540,
            'IN1_offset': 0x017e9000,
            'output1_offset': 0x01915000,
            'param_offset': 0x100003a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 19
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 258},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00018540,
            'IN1_offset': 0x01915000,
            'output1_offset': 0x019ab000,
            'param_offset': 0x100004a0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 20
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 2, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 585},
            'quant_param2': {'shift': 14, 'scale': 409},
            'quant_param3': {'shift': 14, 'scale': 275},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000189c0,
            'IN1_offset': 0x019ab000,
            'output1_offset': 0x019d0800,
            'output2_offset': 0x019f6000,
            'output3_offset': 0x01a1b800,
            'param_offset': 0x100005a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 21
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 139},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0002a9c0,
            'IN1_offset': 0x019e3400,
            'output1_offset': 0x01a66800,
            'param_offset': 0x100007a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 22
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 177},
            'quant_param2': {'shift': 14, 'scale': 118},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000339c0,
            'IN1_offset': 0x01a66800,
            'output1_offset': 0x01a79400,
            'output2_offset': 0x01a8c000,
            'param_offset': 0x10000820,
        },
        'operation': 'D2_CONV',
    },
    # Layer 23
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01a79400,
            'IN2_offset': 0x01a08c00,
            'output1_offset': 0x01a9ec00,
        },
        'operation': 'EWADDER',
    },
    # Layer 24
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 141},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0003c9c0,
            'IN1_offset': 0x01a9ec00,
            'output1_offset': 0x01ab1800,
            'param_offset': 0x100008a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 25
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 162},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000459c0,
            'IN1_offset': 0x01ab1800,
            'output1_offset': 0x01ac4400,
            'param_offset': 0x10000920,
        },
        'operation': 'D2_CONV',
    },
    # Layer 26
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01a8c000,
            'IN2_offset': 0x01a2e400,
            'output1_offset': 0x01a41000,
        },
        'operation': 'EWADDER',
    },
    # Layer 27
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01a41000,
            'IN2_offset': 0x01ac4400,
            'output1_offset': 0x01a53c00,
        },
        'operation': 'EWADDER',
    },
    # Layer 28
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 248},
            'quant_param2': {'shift': 14, 'scale': 242},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0001e9c0,
            'IN1_offset': 0x01a1b800,
            'output1_offset': 0x01ad7000,
            'output2_offset': 0x01b47800,
            'param_offset': 0x100006a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 29
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 266},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0004e9c0,
            'IN1_offset': 0x01ad7000,
            'output1_offset': 0x01b6d000,
            'param_offset': 0x100009a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 30
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 436},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0005a9c0,
            'IN1_offset': 0x01b6d000,
            'output1_offset': 0x01bb8000,
            'param_offset': 0x10000ba0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 31
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 504},
            'quant_param2': {'shift': 14, 'scale': 282},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0005b2c0,
            'IN1_offset': 0x01bb8000,
            'output1_offset': 0x01bcac00,
            'output2_offset': 0x01bdd800,
            'param_offset': 0x10000da0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 32
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 185},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000972c0,
            'IN1_offset': 0x01bd4200,
            'output1_offset': 0x01bf9a00,
            'param_offset': 0x100011a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 33
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 155},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000bb2c0,
            'IN1_offset': 0x01bf9a00,
            'output1_offset': 0x01c03000,
            'param_offset': 0x100012a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 34
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01be6e00,
            'IN2_offset': 0x01c03000,
            'output1_offset': 0x01bf0400,
        },
        'operation': 'EWADDER',
    },
    # Layer 35
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 384, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 198},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000732c0,
            'IN1_offset': 0x01bdd800,
            'output1_offset': 0x01c0c600,
            'param_offset': 0x10000fa0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 36
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 555},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000df2c0,
            'IN1_offset': 0x01c0c600,
            'output1_offset': 0x01c1f200,
            'param_offset': 0x100013a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 37
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 1, 'l_ovlp': 0, 'r_ovlp': 1, 'pad_type': 1, 't_pad': 0, 'b_pad': 1, 'l_pad': 0, 'r_pad': 1},
            'operation_cfg': {'operation': 'MAIN_PRCS', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'MAXPOOL', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01c1f200,
            'output1_offset': 0x01c28800,
        },
        'operation': 'MAIN_PRCS',
    },
    # Layer 38
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 1, 'l_ovlp': 0, 'r_ovlp': 1, 'pad_type': 1, 't_pad': 0, 'b_pad': 1, 'l_pad': 0, 'r_pad': 1},
            'operation_cfg': {'operation': 'MAIN_PRCS', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'MAXPOOL', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01c28800,
            'output1_offset': 0x01c31e00,
        },
        'operation': 'MAIN_PRCS',
    },
    # Layer 39
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 1, 'l_ovlp': 0, 'r_ovlp': 1, 'pad_type': 1, 't_pad': 0, 'b_pad': 1, 'l_pad': 0, 'r_pad': 1},
            'operation_cfg': {'operation': 'MAIN_PRCS', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'MAXPOOL', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01c31e00,
            'output1_offset': 0x01c3b400,
        },
        'operation': 'MAIN_PRCS',
    },
    # Layer 40
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 512, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 181},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x000eb2c0,
            'IN1_offset': 0x01c1f200,
            'output1_offset': 0x01c44a00,
            'param_offset': 0x100014a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 41
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 3, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 376},
            'quant_param2': {'shift': 14, 'scale': 372},
            'quant_param3': {'shift': 14, 'scale': 409},
            'quant_param4': {'shift': 14, 'scale': 409},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0011b2c0,
            'IN1_offset': 0x01c44a00,
            'output1_offset': 0x01c57600,
            'output2_offset': 0x01c6a200,
            'output3_offset': 0x01c7ce00,
            'output4_offset': 0x01c8fa00,
            'param_offset': 0x100016a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 42
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 204},
            'quant_param2': {'shift': 14, 'scale': 1927},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0014b2c0,
            'IN1_offset': 0x01c60c00,
            'output1_offset': 0x01ca2600,
            'output2_offset': 0x01cb5200,
            'param_offset': 0x10001aa0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 43
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'MATMUL', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 16384},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 16, 'scale': 16384},
            'C_CONCAT': 2,
            'weight_offset': 0x01ca2600,
            'IN1_offset': 0x01ca4b80,
            'IN2_offset': 0x01ca7100,
            'output1_offset': 0x01cc7e00,
        },
        'operation': 'MATMUL',
    },
    # Layer 44
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 16, 'tile': 16},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'MATMUL', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 16384},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 16, 'scale': 16384},
            'C_CONCAT': 2,
            'weight_offset': 0x01cabc00,
            'IN1_offset': 0x01cae180,
            'IN2_offset': 0x01cb0700,
            'output1_offset': 0x01ccc900,
        },
        'operation': 'MATMUL',
    },
    # Layer 45
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 819},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0015d2c0,
            'IN1_offset': 0x01cb9d00,
            'output1_offset': 0x01cd1400,
            'param_offset': 0x10001da0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 46
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 819},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0015d500,
            'IN1_offset': 0x01cc3300,
            'output1_offset': 0x01cd5f00,
            'param_offset': 0x10001e20,
        },
        'operation': 'DW_CONV',
    },
    # Layer 47
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01cc7e00,
            'IN2_offset': 0x01cd1400,
            'output1_offset': 0x01cdaa00,
        },
        'operation': 'EWADDER',
    },
    # Layer 48
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 104},
            'quant_param2': {'shift': 14, 'scale': 114},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001572c0,
            'IN1_offset': 0x01cdaa00,
            'output1_offset': 0x01ce4000,
            'output2_offset': 0x01ced600,
            'param_offset': 0x10001ca0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 49
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01c73800,
            'IN2_offset': 0x01ce4000,
            'output1_offset': 0x01cf6c00,
        },
        'operation': 'EWADDER',
    },
    # Layer 50
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 327},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x0015d740,
            'IN1_offset': 0x01cf6c00,
            'output1_offset': 0x01d00200,
            'param_offset': 0x10001ea0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 51
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 133},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00169740,
            'IN1_offset': 0x01d00200,
            'output1_offset': 0x01d12e00,
            'param_offset': 0x100020a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 52
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01c86400,
            'IN2_offset': 0x01ced600,
            'output1_offset': 0x01d1c400,
        },
        'operation': 'EWADDER',
    },
    # Layer 53
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01d1c400,
            'IN2_offset': 0x01d12e00,
            'output1_offset': 0x01c99000,
        },
        'operation': 'EWADDER',
    },
    # Layer 54
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 264},
            'quant_param2': {'shift': 14, 'scale': 260},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001332c0,
            'IN1_offset': 0x01c8fa00,
            'output1_offset': 0x01d25a00,
            'output2_offset': 0x01d41c00,
            'param_offset': 0x100018a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 55
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'RESIZE', 'kernel_size': 2, 'stride': 1, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01d25a00,
            'output1_offset': 0x01afc800,
        },
        'operation': 'RESIZE',
    },
    # Layer 56
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 384, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 312},
            'quant_param2': {'shift': 14, 'scale': 234},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00175740,
            'IN1_offset': 0x01afc800,
            'output1_offset': 0x01d54800,
            'output2_offset': 0x01d7a000,
            'param_offset': 0x100021a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 57
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 164},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00190740,
            'IN1_offset': 0x01d67400,
            'output1_offset': 0x01db2400,
            'param_offset': 0x100023a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 58
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 166},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00199740,
            'IN1_offset': 0x01db2400,
            'output1_offset': 0x01d9f800,
            'param_offset': 0x10002420,
        },
        'operation': 'D2_CONV',
    },
    # Layer 59
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 192, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 187},
            'quant_param2': {'shift': 14, 'scale': 218},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00187740,
            'IN1_offset': 0x01d7a000,
            'output1_offset': 0x01dc5000,
            'output2_offset': 0x01dea800,
            'param_offset': 0x100022a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 60
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'RESIZE', 'kernel_size': 2, 'stride': 1, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x01e10000,
            'output1_offset': 0x01834000,
        },
        'operation': 'RESIZE',
    },
    # Layer 61
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 192, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 668},
            'quant_param2': {'shift': 14, 'scale': 442},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001a2740,
            'IN1_offset': 0x01834000,
            'output1_offset': 0x01e22c00,
            'output2_offset': 0x01e6dc00,
            'param_offset': 0x100024a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 62
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 171},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001a9340,
            'IN1_offset': 0x01e48400,
            'output1_offset': 0x01ede400,
            'param_offset': 0x100025a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 63
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 32, 'tile': 32},
            'tile_out_ch': {'total': 32, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 280},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001ab740,
            'IN1_offset': 0x01ede400,
            'output1_offset': 0x01eb8c00,
            'param_offset': 0x100025e0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 64
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 96, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 461},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001a6f40,
            'IN1_offset': 0x01e6dc00,
            'output1_offset': 0x01f03c00,
            'param_offset': 0x10002520,
        },
        'operation': 'D2_CONV',
    },
    # Layer 65
    {
        'params': {
            'tile_height': {'total': 80, 'tile': 20},
            'tile_width': {'total': 60, 'tile': 20},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 112},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001adb40,
            'IN1_offset': 0x01f03c00,
            'output1_offset': 0x01e10000,
            'param_offset': 0x10002620,
        },
        'operation': 'D2_CONV',
    },
    # Layer 66
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 192, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 360},
            'quant_param2': {'shift': 14, 'scale': 239},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001b6b40,
            'IN1_offset': 0x01dea800,
            'output1_offset': 0x01f4ec00,
            'output2_offset': 0x01f74400,
            'param_offset': 0x100026a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 67
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 192},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001c8b40,
            'IN1_offset': 0x01f61800,
            'output1_offset': 0x01fac800,
            'param_offset': 0x100028a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 68
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 64, 'tile': 32},
            'tile_out_ch': {'total': 64, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 211},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001d1b40,
            'IN1_offset': 0x01fac800,
            'output1_offset': 0x01f99c00,
            'param_offset': 0x10002920,
        },
        'operation': 'D2_CONV',
    },
    # Layer 69
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 192, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 630},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001bfb40,
            'IN1_offset': 0x01f74400,
            'output1_offset': 0x01fbf400,
            'param_offset': 0x100027a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 70
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 420},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001dab40,
            'IN1_offset': 0x01fbf400,
            'output1_offset': 0x01fe4c00,
            'param_offset': 0x100029a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 71
    {
        'params': {
            'tile_height': {'total': 40, 'tile': 20},
            'tile_width': {'total': 30, 'tile': 30},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 0, 'l_ovlp': 1, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 1, 'b_pad': 0, 'l_pad': 1, 'r_pad': 0},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 2, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 315},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001e0b40,
            'IN1_offset': 0x01fe4c00,
            'output1_offset': 0x01d38600,
            'param_offset': 0x10002aa0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 72
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 384, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 1, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 520},
            'quant_param2': {'shift': 14, 'scale': 191},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x001e0fc0,
            'IN1_offset': 0x01d38600,
            'output1_offset': 0x0200a400,
            'output2_offset': 0x0201d000,
            'param_offset': 0x10002ba0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 73
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 840},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00228fc0,
            'IN1_offset': 0x02013a00,
            'output1_offset': 0x02039200,
            'param_offset': 0x10002fa0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 74
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 128, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 496},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00229440,
            'IN1_offset': 0x02039200,
            'output1_offset': 0x02042800,
            'param_offset': 0x100030a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 75
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 455},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00235440,
            'IN1_offset': 0x02042800,
            'output1_offset': 0x02055400,
            'param_offset': 0x100032a0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 76
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 256, 'tile': 32},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 431},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00235d40,
            'IN1_offset': 0x02055400,
            'output1_offset': 0x02068000,
            'param_offset': 0x100034a0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 77
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 1, 'b_ovlp': 1, 'l_ovlp': 1, 'r_ovlp': 1, 'pad_type': 0, 't_pad': 1, 'b_pad': 1, 'l_pad': 1, 'r_pad': 1},
            'operation_cfg': {'operation': 'DW_CONV', 'kernel_size': 3, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 425},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00241d40,
            'IN1_offset': 0x02068000,
            'output1_offset': 0x02071600,
            'param_offset': 0x100035a0,
        },
        'operation': 'DW_CONV',
    },
    # Layer 78
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 4, 'tile': 4},
            'tile_out_ch': {'total': 128, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'EWADDER', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'IN1_offset': 0x02026600,
            'IN2_offset': 0x02071600,
            'output1_offset': 0x0202fc00,
        },
        'operation': 'EWADDER',
    },
    # Layer 79
    {
        'params': {
            'tile_height': {'total': 20, 'tile': 20},
            'tile_width': {'total': 15, 'tile': 15},
            'tile_in_ch': {'total': 384, 'tile': 32},
            'tile_out_ch': {'total': 256, 'tile': 32},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 1, 'stride': 1, 'post_valid': 1, 'branch': 0, 'q_method': 7},
            'post_process_cfg': {'active_slope': 3, 'mp_stride': 0, 'prcs1': 'ADD', 'prcs2': 'ACTIVE', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 14, 'scale': 474},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
            'weight_offset': 0x00204fc0,
            'IN1_offset': 0x0201d000,
            'output1_offset': 0x0207ac00,
            'param_offset': 0x10002da0,
        },
        'operation': 'D2_CONV',
    },
    # Layer 80
    {
        'params': {
            'tile_height': {'total': 0, 'tile': 0},
            'tile_width': {'total': 0, 'tile': 0},
            'tile_in_ch': {'total': 0, 'tile': 0},
            'tile_out_ch': {'total': 0, 'tile': 0},
            'pad_cfg': {'t_ovlp': 0, 'b_ovlp': 0, 'l_ovlp': 0, 'r_ovlp': 0, 'pad_type': 0, 't_pad': 0, 'b_pad': 0, 'l_pad': 0, 'r_pad': 0},
            'operation_cfg': {'operation': 'D2_CONV', 'kernel_size': 0, 'stride': 0, 'post_valid': 0, 'branch': 0, 'q_method': 0},
            'post_process_cfg': {'active_slope': 0, 'mp_stride': 0, 'prcs1': '0', 'prcs2': '0', 'prcs3': '0', 'prcs4': '0'},
            'quant_param1': {'shift': 0, 'scale': 0},
            'quant_param2': {'shift': 0, 'scale': 0},
            'quant_param3': {'shift': 0, 'scale': 0},
            'quant_param4': {'shift': 0, 'scale': 0},
            'quant_param_qk': {'shift': 0, 'scale': 0},
            'C_CONCAT': 2,
        },
        'operation': 'D2_CONV',
    },
]
