from MSIS_NPU_Instruction_SetV1.InstructionSet_Microcode import *

########################
#        layer0        #
########################
# ConvAct0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   16,    16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      480,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     640,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 127)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00000000)
offset_write(OPCODE["LD_IN1"],    0x01000000)
offset_write(OPCODE["LD_PARAM"],  0x10000000)
offset_write(OPCODE["ST_OUT1"],   0x0112c000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer1        #
########################
# ConvAct1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    16,     16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      240,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     320,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 277)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00000240)
offset_write(OPCODE["LD_IN1"],    0x0112c000)
offset_write(OPCODE["LD_PARAM"],  0x10000020)
offset_write(OPCODE["ST_OUT1"],   0x01258000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer2        #
########################
# ConvAct2
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      120,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     160,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 1129)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 455)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00001440)
offset_write(OPCODE["LD_IN1"],    0x01258000)
offset_write(OPCODE["LD_PARAM"],  0x10000060)
offset_write(OPCODE["ST_OUT1"],   0x012ee000)
offset_write(OPCODE["ST_OUT2"],   0x01384000)
ctrl_write(OPCODE["LYREND"])
# ConvAct4
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   16,    16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    16,     16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      120,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     160,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 512)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00002340)
offset_write(OPCODE["LD_IN1"],    0x01339000)
offset_write(OPCODE["LD_PARAM"],  0x100000e0)
offset_write(OPCODE["ST_OUT1"],   0x01465000)
ctrl_write(OPCODE["LYREND"])
# ConvAct5
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   16,    16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    16,     16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      120,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     160,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 149)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00002c40)
offset_write(OPCODE["LD_IN1"],    0x01465000)
offset_write(OPCODE["LD_PARAM"],  0x10000100)
offset_write(OPCODE["ST_OUT1"],   0x014b0000)
ctrl_write(OPCODE["LYREND"])
# EWAdder0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   16,   16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      120,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     160,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x014b0000)
offset_write(OPCODE["LD_IN2"],    0x013cf000)
offset_write(OPCODE["ST_OUT1"],   0x0141a000)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct3
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    48,     16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      120,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     160,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 489)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00001a40)
offset_write(OPCODE["LD_IN1"],    0x01384000)
offset_write(OPCODE["LD_PARAM"],  0x100000a0)
offset_write(OPCODE["ST_OUT1"],   0x014fb000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer3        #
########################
# ConvAct6
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      120,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     160,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 196)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00003540)
offset_write(OPCODE["LD_IN1"],    0x014fb000)
offset_write(OPCODE["LD_PARAM"],  0x10000120)
offset_write(OPCODE["ST_OUT1"],   0x01591000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer4        #
########################
# ConvAct7
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 630)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 436)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM3"], 14, 227)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 2,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00007d40)
offset_write(OPCODE["LD_IN1"],    0x01591000)
offset_write(OPCODE["LD_PARAM"],  0x100001a0)
offset_write(OPCODE["ST_OUT1"],   0x015dc000)
offset_write(OPCODE["ST_OUT2"],   0x01627000)
offset_write(OPCODE["ST_OUT3"],   0x01672000)
ctrl_write(OPCODE["LYREND"])
# ConvAct9
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 157)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0000c540)
offset_write(OPCODE["LD_IN1"],    0x01601800)
offset_write(OPCODE["LD_PARAM"],  0x100002a0)
offset_write(OPCODE["ST_OUT1"],   0x01708000)
ctrl_write(OPCODE["LYREND"])
# ConvAct10
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 135)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 70)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0000e940)
offset_write(OPCODE["LD_IN1"],    0x01708000)
offset_write(OPCODE["LD_PARAM"],  0x100002e0)
offset_write(OPCODE["ST_OUT1"],   0x0172d800)
offset_write(OPCODE["ST_OUT2"],   0x01753000)
ctrl_write(OPCODE["LYREND"])
# EWAdder0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x0172d800)
offset_write(OPCODE["LD_IN2"],    0x0164c800)
offset_write(OPCODE["ST_OUT1"],   0x01778800)
ctrl_write(OPCODE["LYREND"])
# ConvAct11
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 221)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00010d40)
offset_write(OPCODE["LD_IN1"],    0x01778800)
offset_write(OPCODE["LD_PARAM"],  0x10000320)
offset_write(OPCODE["ST_OUT1"],   0x0179e000)
ctrl_write(OPCODE["LYREND"])
# ConvAct12
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 158)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00013140)
offset_write(OPCODE["LD_IN1"],    0x0179e000)
offset_write(OPCODE["LD_PARAM"],  0x10000360)
offset_write(OPCODE["ST_OUT1"],   0x017c3800)
ctrl_write(OPCODE["LYREND"])
# EWAdder1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01753000)
offset_write(OPCODE["LD_IN2"],    0x01697800)
offset_write(OPCODE["ST_OUT1"],   0x016bd000)
ctrl_write(OPCODE["LYREND"])
# EWAdder2
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x016bd000)
offset_write(OPCODE["LD_IN2"],    0x017c3800)
offset_write(OPCODE["ST_OUT1"],   0x016e2800)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct8
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 352)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 344)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00009540)
offset_write(OPCODE["LD_IN1"],    0x01672000)
offset_write(OPCODE["LD_PARAM"],  0x10000220)
offset_write(OPCODE["ST_OUT1"],   0x017e9000)
offset_write(OPCODE["ST_OUT2"],   0x018ca000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer5        #
########################
# ConvAct13
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 390)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00015540)
offset_write(OPCODE["LD_IN1"],    0x017e9000)
offset_write(OPCODE["LD_PARAM"],  0x100003a0)
offset_write(OPCODE["ST_OUT1"],   0x01915000)
ctrl_write(OPCODE["LYREND"])
# Conv14
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 258)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x00018540)
offset_write(OPCODE["LD_IN1"],    0x01915000)
offset_write(OPCODE["LD_PARAM"],  0x100004a0)
offset_write(OPCODE["ST_OUT1"],   0x019ab000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer6        #
########################
# ConvAct15
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 585)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 409)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM3"], 14, 275)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 2,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000189c0)
offset_write(OPCODE["LD_IN1"],    0x019ab000)
offset_write(OPCODE["LD_PARAM"],  0x100005a0)
offset_write(OPCODE["ST_OUT1"],   0x019d0800)
offset_write(OPCODE["ST_OUT2"],   0x019f6000)
offset_write(OPCODE["ST_OUT3"],   0x01a1b800)
ctrl_write(OPCODE["LYREND"])
# ConvAct17
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 139)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0002a9c0)
offset_write(OPCODE["LD_IN1"],    0x019e3400)
offset_write(OPCODE["LD_PARAM"],  0x100007a0)
offset_write(OPCODE["ST_OUT1"],   0x01a66800)
ctrl_write(OPCODE["LYREND"])
# ConvAct18
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 177)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 118)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000339c0)
offset_write(OPCODE["LD_IN1"],    0x01a66800)
offset_write(OPCODE["LD_PARAM"],  0x10000820)
offset_write(OPCODE["ST_OUT1"],   0x01a79400)
offset_write(OPCODE["ST_OUT2"],   0x01a8c000)
ctrl_write(OPCODE["LYREND"])
# EWAdder0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01a79400)
offset_write(OPCODE["LD_IN2"],    0x01a08c00)
offset_write(OPCODE["ST_OUT1"],   0x01a9ec00)
ctrl_write(OPCODE["LYREND"])
# ConvAct19
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 141)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0003c9c0)
offset_write(OPCODE["LD_IN1"],    0x01a9ec00)
offset_write(OPCODE["LD_PARAM"],  0x100008a0)
offset_write(OPCODE["ST_OUT1"],   0x01ab1800)
ctrl_write(OPCODE["LYREND"])
# ConvAct20
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 162)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000459c0)
offset_write(OPCODE["LD_IN1"],    0x01ab1800)
offset_write(OPCODE["LD_PARAM"],  0x10000920)
offset_write(OPCODE["ST_OUT1"],   0x01ac4400)
ctrl_write(OPCODE["LYREND"])
# EWAdder1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01a8c000)
offset_write(OPCODE["LD_IN2"],    0x01a2e400)
offset_write(OPCODE["ST_OUT1"],   0x01a41000)
ctrl_write(OPCODE["LYREND"])
# EWAdder2
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01a41000)
offset_write(OPCODE["LD_IN2"],    0x01ac4400)
offset_write(OPCODE["ST_OUT1"],   0x01a53c00)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct16
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 248)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 242)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0001e9c0)
offset_write(OPCODE["LD_IN1"],    0x01a1b800)
offset_write(OPCODE["LD_PARAM"],  0x100006a0)
offset_write(OPCODE["ST_OUT1"],   0x01ad7000)
offset_write(OPCODE["ST_OUT2"],   0x01b47800)
ctrl_write(OPCODE["LYREND"])

########################
#        layer7        #
########################
# ConvAct21
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 266)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0004e9c0)
offset_write(OPCODE["LD_IN1"],    0x01ad7000)
offset_write(OPCODE["LD_PARAM"],  0x100009a0)
offset_write(OPCODE["ST_OUT1"],   0x01b6d000)
ctrl_write(OPCODE["LYREND"])
# Conv22
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 436)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x0005a9c0)
offset_write(OPCODE["LD_IN1"],    0x01b6d000)
offset_write(OPCODE["LD_PARAM"],  0x10000ba0)
offset_write(OPCODE["ST_OUT1"],   0x01bb8000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer8        #
########################
# ConvAct23
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 504)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 282)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0005b2c0)
offset_write(OPCODE["LD_IN1"],    0x01bb8000)
offset_write(OPCODE["LD_PARAM"],  0x10000da0)
offset_write(OPCODE["ST_OUT1"],   0x01bcac00)
offset_write(OPCODE["ST_OUT2"],   0x01bdd800)
ctrl_write(OPCODE["LYREND"])
# ConvAct25
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 185)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000972c0)
offset_write(OPCODE["LD_IN1"],    0x01bd4200)
offset_write(OPCODE["LD_PARAM"],  0x100011a0)
offset_write(OPCODE["ST_OUT1"],   0x01bf9a00)
ctrl_write(OPCODE["LYREND"])
# ConvAct26
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 155)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000bb2c0)
offset_write(OPCODE["LD_IN1"],    0x01bf9a00)
offset_write(OPCODE["LD_PARAM"],  0x100012a0)
offset_write(OPCODE["ST_OUT1"],   0x01c03000)
ctrl_write(OPCODE["LYREND"])
# EWAdder0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01be6e00)
offset_write(OPCODE["LD_IN2"],    0x01c03000)
offset_write(OPCODE["ST_OUT1"],   0x01bf0400)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct24
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    384,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 198)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000732c0)
offset_write(OPCODE["LD_IN1"],    0x01bdd800)
offset_write(OPCODE["LD_PARAM"],  0x10000fa0)
offset_write(OPCODE["ST_OUT1"],   0x01c0c600)
ctrl_write(OPCODE["LYREND"])

########################
#        layer9        #
########################
# ConvAct27
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 555)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000df2c0)
offset_write(OPCODE["LD_IN1"],    0x01c0c600)
offset_write(OPCODE["LD_PARAM"],  0x100013a0)
offset_write(OPCODE["ST_OUT1"],   0x01c1f200)
ctrl_write(OPCODE["LYREND"])
# MaxPool1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,1,0,1, 1, 0,1,0,1)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["MAIN_PRCS"], 0,0,0,0,    POST_PROC["MAXPOOL"],False,False,False)
offset_write(OPCODE["LD_IN1"],    0x01c1f200)
offset_write(OPCODE["ST_OUT1"],   0x01c28800)
ctrl_write(OPCODE["LYREND"])
# MaxPool2
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,1,0,1, 1, 0,1,0,1)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["MAIN_PRCS"], 0,0,0,0,    POST_PROC["MAXPOOL"],False,False,False)
offset_write(OPCODE["LD_IN1"],    0x01c28800)
offset_write(OPCODE["ST_OUT1"],   0x01c31e00)
ctrl_write(OPCODE["LYREND"])
# MaxPool3
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,1,0,1, 1, 0,1,0,1)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["MAIN_PRCS"], 0,0,0,0,    POST_PROC["MAXPOOL"],False,False,False)
offset_write(OPCODE["LD_IN1"],    0x01c31e00)
offset_write(OPCODE["ST_OUT1"],   0x01c3b400)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct28
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    512,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 181)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x000eb2c0)
offset_write(OPCODE["LD_IN1"],    0x01c1f200)
offset_write(OPCODE["LD_PARAM"],  0x100014a0)
offset_write(OPCODE["ST_OUT1"],   0x01c44a00)
ctrl_write(OPCODE["LYREND"])

########################
#        layer10        #
########################
# ConvAct29
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 376)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 372)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM3"], 14, 409)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM4"], 14, 409)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 3,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0011b2c0)
offset_write(OPCODE["LD_IN1"],    0x01c44a00)
offset_write(OPCODE["LD_PARAM"],  0x100016a0)
offset_write(OPCODE["ST_OUT1"],   0x01c57600)
offset_write(OPCODE["ST_OUT2"],   0x01c6a200)
offset_write(OPCODE["ST_OUT3"],   0x01c7ce00)
offset_write(OPCODE["ST_OUT4"],   0x01c8fa00)
ctrl_write(OPCODE["LYREND"])
# Conv31
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 204)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 1927)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x0014b2c0)
offset_write(OPCODE["LD_IN1"],    0x01c60c00)
offset_write(OPCODE["LD_PARAM"],  0x10001aa0)
offset_write(OPCODE["ST_OUT1"],   0x01ca2600)
offset_write(OPCODE["ST_OUT2"],   0x01cb5200)
ctrl_write(OPCODE["LYREND"])
# AttnHead0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,      0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   16,     16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
qparam_write(OPCODE["SETREG"], OPERAND1["QU_PARAM_QK"], 16, 16384)
qparam_write(OPCODE["SETREG"], OPERAND1["QU_PARAM1"], 14, 16384)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["MATMUL"],    0,0,0, 0,7, 0)
offset_write(OPCODE["LD_WGT"],  0x01ca2600)
offset_write(OPCODE["LD_IN1"],  0x01ca4b80)
offset_write(OPCODE["LD_IN2"],  0x01ca7100)
offset_write(OPCODE["ST_OUT1"], 0x01cc7e00)
ctrl_write(OPCODE["LYREND"])
# AttnHead1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,      0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   16,     16)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
qparam_write(OPCODE["SETREG"], OPERAND1["QU_PARAM_QK"], 16, 16384)
qparam_write(OPCODE["SETREG"], OPERAND1["QU_PARAM1"], 14, 16384)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["MATMUL"],    0,0,0, 0,7, 0)
offset_write(OPCODE["LD_WGT"],  0x01cabc00)
offset_write(OPCODE["LD_IN1"],  0x01cae180)
offset_write(OPCODE["LD_IN2"],  0x01cb0700)
offset_write(OPCODE["ST_OUT1"], 0x01ccc900)
ctrl_write(OPCODE["LYREND"])
# Conv33_Head0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 819)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x0015d2c0)
offset_write(OPCODE["LD_IN1"],    0x01cb9d00)
offset_write(OPCODE["LD_PARAM"],  0x10001da0)
offset_write(OPCODE["ST_OUT1"],   0x01cd1400)
ctrl_write(OPCODE["LYREND"])
# Conv33_Head1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 819)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x0015d500)
offset_write(OPCODE["LD_IN1"],    0x01cc3300)
offset_write(OPCODE["LD_PARAM"],  0x10001e20)
offset_write(OPCODE["ST_OUT1"],   0x01cd5f00)
ctrl_write(OPCODE["LYREND"])
# EWAdder0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01cc7e00)
offset_write(OPCODE["LD_IN2"],    0x01cd1400)
offset_write(OPCODE["ST_OUT1"],   0x01cdaa00)
ctrl_write(OPCODE["LYREND"])
# Conv32
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 104)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 114)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x001572c0)
offset_write(OPCODE["LD_IN1"],    0x01cdaa00)
offset_write(OPCODE["LD_PARAM"],  0x10001ca0)
offset_write(OPCODE["ST_OUT1"],   0x01ce4000)
offset_write(OPCODE["ST_OUT2"],   0x01ced600)
ctrl_write(OPCODE["LYREND"])
# EWAdder1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01c73800)
offset_write(OPCODE["LD_IN2"],    0x01ce4000)
offset_write(OPCODE["ST_OUT1"],   0x01cf6c00)
ctrl_write(OPCODE["LYREND"])
# ConvAct34
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 327)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x0015d740)
offset_write(OPCODE["LD_IN1"],    0x01cf6c00)
offset_write(OPCODE["LD_PARAM"],  0x10001ea0)
offset_write(OPCODE["ST_OUT1"],   0x01d00200)
ctrl_write(OPCODE["LYREND"])
# Conv35
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 133)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x00169740)
offset_write(OPCODE["LD_IN1"],    0x01d00200)
offset_write(OPCODE["LD_PARAM"],  0x100020a0)
offset_write(OPCODE["ST_OUT1"],   0x01d12e00)
ctrl_write(OPCODE["LYREND"])
# EWAdder2
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01c86400)
offset_write(OPCODE["LD_IN2"],    0x01ced600)
offset_write(OPCODE["ST_OUT1"],   0x01d1c400)
ctrl_write(OPCODE["LYREND"])
# EWAdder3
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01d1c400)
offset_write(OPCODE["LD_IN2"],    0x01d12e00)
offset_write(OPCODE["ST_OUT1"],   0x01c99000)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct30
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 264)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 260)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001332c0)
offset_write(OPCODE["LD_IN1"],    0x01c8fa00)
offset_write(OPCODE["LD_PARAM"],  0x100018a0)
offset_write(OPCODE["ST_OUT1"],   0x01d25a00)
offset_write(OPCODE["ST_OUT2"],   0x01d41c00)
ctrl_write(OPCODE["LYREND"])

########################
#        layer11        #
########################
# Upsample0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["RESIZE"],       2,1,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01d25a00)
offset_write(OPCODE["ST_OUT1"],   0x01afc800)
ctrl_write(OPCODE["LYREND"])

########################
#        layer12        #
########################
# Concatenation

########################
#        layer13        #
########################
# ConvAct36
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    384,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 312)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 234)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00175740)
offset_write(OPCODE["LD_IN1"],    0x01afc800)
offset_write(OPCODE["LD_PARAM"],  0x100021a0)
offset_write(OPCODE["ST_OUT1"],   0x01d54800)
offset_write(OPCODE["ST_OUT2"],   0x01d7a000)
ctrl_write(OPCODE["LYREND"])
# ConvAct38
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 164)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00190740)
offset_write(OPCODE["LD_IN1"],    0x01d67400)
offset_write(OPCODE["LD_PARAM"],  0x100023a0)
offset_write(OPCODE["ST_OUT1"],   0x01db2400)
ctrl_write(OPCODE["LYREND"])
# ConvAct39
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 166)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00199740)
offset_write(OPCODE["LD_IN1"],    0x01db2400)
offset_write(OPCODE["LD_PARAM"],  0x10002420)
offset_write(OPCODE["ST_OUT1"],   0x01d9f800)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct37
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    192,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 187)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 218)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00187740)
offset_write(OPCODE["LD_IN1"],    0x01d7a000)
offset_write(OPCODE["LD_PARAM"],  0x100022a0)
offset_write(OPCODE["ST_OUT1"],   0x01dc5000)
offset_write(OPCODE["ST_OUT2"],   0x01dea800)
ctrl_write(OPCODE["LYREND"])

########################
#        layer14        #
########################
# Upsample1
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["RESIZE"],       2,1,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x01e10000)
offset_write(OPCODE["ST_OUT1"],   0x01834000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer15        #
########################
# Concatenation

########################
#        layer16        #
########################
# ConvAct40
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    192,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 668)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 442)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001a2740)
offset_write(OPCODE["LD_IN1"],    0x01834000)
offset_write(OPCODE["LD_PARAM"],  0x100024a0)
offset_write(OPCODE["ST_OUT1"],   0x01e22c00)
offset_write(OPCODE["ST_OUT2"],   0x01e6dc00)
ctrl_write(OPCODE["LYREND"])
# ConvAct42
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 171)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001a9340)
offset_write(OPCODE["LD_IN1"],    0x01e48400)
offset_write(OPCODE["LD_PARAM"],  0x100025a0)
offset_write(OPCODE["ST_OUT1"],   0x01ede400)
ctrl_write(OPCODE["LYREND"])
# ConvAct43
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   32,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    32,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 280)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001ab740)
offset_write(OPCODE["LD_IN1"],    0x01ede400)
offset_write(OPCODE["LD_PARAM"],  0x100025e0)
offset_write(OPCODE["ST_OUT1"],   0x01eb8c00)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct41
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    96,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 461)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001a6f40)
offset_write(OPCODE["LD_IN1"],    0x01e6dc00)
offset_write(OPCODE["LD_PARAM"],  0x10002520)
offset_write(OPCODE["ST_OUT1"],   0x01f03c00)
ctrl_write(OPCODE["LYREND"])

########################
#        layer17        #
########################
# ConvAct44
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      60,   20)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     80,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 112)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001adb40)
offset_write(OPCODE["LD_IN1"],    0x01f03c00)
offset_write(OPCODE["LD_PARAM"],  0x10002620)
offset_write(OPCODE["ST_OUT1"],   0x01e10000)
ctrl_write(OPCODE["LYREND"])

########################
#        layer18        #
########################
# Concatenation

########################
#        layer19        #
########################
# ConvAct45
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    192,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 360)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 239)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001b6b40)
offset_write(OPCODE["LD_IN1"],    0x01dea800)
offset_write(OPCODE["LD_PARAM"],  0x100026a0)
offset_write(OPCODE["ST_OUT1"],   0x01f4ec00)
offset_write(OPCODE["ST_OUT2"],   0x01f74400)
ctrl_write(OPCODE["LYREND"])
# ConvAct47
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 192)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001c8b40)
offset_write(OPCODE["LD_IN1"],    0x01f61800)
offset_write(OPCODE["LD_PARAM"],  0x100028a0)
offset_write(OPCODE["ST_OUT1"],   0x01fac800)
ctrl_write(OPCODE["LYREND"])
# ConvAct48
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   64,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    64,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 211)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001d1b40)
offset_write(OPCODE["LD_IN1"],    0x01fac800)
offset_write(OPCODE["LD_PARAM"],  0x10002920)
offset_write(OPCODE["ST_OUT1"],   0x01f99c00)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct46
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    192,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 630)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001bfb40)
offset_write(OPCODE["LD_IN1"],    0x01f74400)
offset_write(OPCODE["LD_PARAM"],  0x100027a0)
offset_write(OPCODE["ST_OUT1"],   0x01fbf400)
ctrl_write(OPCODE["LYREND"])

########################
#        layer20        #
########################
# ConvAct49
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 420)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001dab40)
offset_write(OPCODE["LD_IN1"],    0x01fbf400)
offset_write(OPCODE["LD_PARAM"],  0x100029a0)
offset_write(OPCODE["ST_OUT1"],   0x01fe4c00)
ctrl_write(OPCODE["LYREND"])
# Conv50
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      30,   30)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     40,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,0,1,0, 0, 1,0,1,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 315)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,2,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 0,0,0,0,    POST_PROC["ADD"],False,False,False)
offset_write(OPCODE["LD_WGT"],    0x001e0b40)
offset_write(OPCODE["LD_IN1"],    0x01fe4c00)
offset_write(OPCODE["LD_PARAM"],  0x10002aa0)
offset_write(OPCODE["ST_OUT1"],   0x01d38600)
ctrl_write(OPCODE["LYREND"])

########################
#        layer21        #
########################
# Concatenation

########################
#        layer22        #
########################
# ConvAct51
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    384,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 520)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM2"], 14, 191)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 1,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x001e0fc0)
offset_write(OPCODE["LD_IN1"],    0x01d38600)
offset_write(OPCODE["LD_PARAM"],  0x10002ba0)
offset_write(OPCODE["ST_OUT1"],   0x0200a400)
offset_write(OPCODE["ST_OUT2"],   0x0201d000)
ctrl_write(OPCODE["LYREND"])
# ConvAct53
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 840)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00228fc0)
offset_write(OPCODE["LD_IN1"],    0x02013a00)
offset_write(OPCODE["LD_PARAM"],  0x10002fa0)
offset_write(OPCODE["ST_OUT1"],   0x02039200)
ctrl_write(OPCODE["LYREND"])
# ConvAct54
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    128,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 496)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00229440)
offset_write(OPCODE["LD_IN1"],    0x02039200)
offset_write(OPCODE["LD_PARAM"],  0x100030a0)
offset_write(OPCODE["ST_OUT1"],   0x02042800)
ctrl_write(OPCODE["LYREND"])
# ConvAct55
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 455)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00235440)
offset_write(OPCODE["LD_IN1"],    0x02042800)
offset_write(OPCODE["LD_PARAM"],  0x100032a0)
offset_write(OPCODE["ST_OUT1"],   0x02055400)
ctrl_write(OPCODE["LYREND"])
# ConvAct56
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    256,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 431)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00235d40)
offset_write(OPCODE["LD_IN1"],    0x02055400)
offset_write(OPCODE["LD_PARAM"],  0x100034a0)
offset_write(OPCODE["ST_OUT1"],   0x02068000)
ctrl_write(OPCODE["LYREND"])
# ConvAct57
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,     4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   1,1,1,1, 0, 1,1,1,1)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 425)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["DW_CONV"],    3,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00241d40)
offset_write(OPCODE["LD_IN1"],    0x02068000)
offset_write(OPCODE["LD_PARAM"],  0x100035a0)
offset_write(OPCODE["ST_OUT1"],   0x02071600)
ctrl_write(OPCODE["LYREND"])
# EWAdder0
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   128,   32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    4,    4)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["EWADDER"],       0,0,0, 0,0, 0)
offset_write(OPCODE["LD_IN1"],    0x02026600)
offset_write(OPCODE["LD_IN2"],    0x02071600)
offset_write(OPCODE["ST_OUT1"],   0x0202fc00)
ctrl_write(OPCODE["LYREND"])
# Concatenation
# ConvAct52
ctrl_write(OPCODE["INIT"])
setreg_write(OPCODE["SETREG"], OPERAND1["CURRENT_LYR"],   0,     0)
setreg_write(OPCODE["SETREG"], OPERAND1["OUT_CHANNEL"],   256,    32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_CHANNEL"],    384,     32)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_WIDTH"],      15,   15)
setreg_write(OPCODE["SETREG"], OPERAND1["IN_HEIGHT"],     20,  20)
ovppad_write(OPCODE["SETREG"], OPERAND1["OVERLAP_PAD"],   0,0,0,0, 0, 0,0,0,0)
qparam_write(OPCODE["SETREG"], OPERAND1[f"QU_PARAM1"], 14, 474)
mainop_write(OPCODE["OPTYPE"], FUNC_PARAM["D2_CONV"],    1,1,1, 0,7, 0)
postop_write(OPCODE["OPTYPE"], FUNC_PARAM["POST_PRCS"], 3,0,0,0,    POST_PROC["ADD"],POST_PROC["ACTIVE"],False,False)
offset_write(OPCODE["LD_WGT"],    0x00204fc0)
offset_write(OPCODE["LD_IN1"],    0x0201d000)
offset_write(OPCODE["LD_PARAM"],  0x10002da0)
offset_write(OPCODE["ST_OUT1"],   0x0207ac00)
ctrl_write(OPCODE["LYREND"])
ctrl_write(OPCODE["FINISH"])